### ISSUE TITLE
Beta build ZIP files don't extract properly on Linux, latest beta build doesn't work on Arch Linux

### ISSUE THREAD

**Issue by ajshell1** [discimagechef/DiscImageChef#225]
So, I tried extracting the latest beta version that is available from the dropbox page. I was using Ark to extract it on KDE on Arch Linux.
This is what happened:

https://pastebin.com/8miCyrPw

In other words, it mistook the directory seperators for actual backslashes in the filename.

I managed to get it properly extracted on Windows, but now it doesn't run period:
Logs: 
https://pastebin.com/s0x2knsf

I have mono installed. The latest stable release runs perfectly fine.

**Comment by claunia** [comment]
As for them being extracted incorrectly using Ark, it's a bug with Ark. Info-Zip extracts them correctly. ZIP applications are expected to treat files marked as created from DOS using \ as path separator.

As for the exception, the beta version is compiled for Windows, so it's crashing on you because it's missing a Linux library for sqlite.

You can get the library downloading the nupkg from https://www.nuget.org/packages/SQLitePCLRaw.lib.e_sqlite3.linux/ and extracting it. Then pick the .so in the folder appropriate to your architecture and just place it in the same folder as DiscImageChef.

Unfortunately I do not know of any way to automate the inclusion of this library in the CI build, but next release will include it.
